#!/usr/bin/env bash
# =============================================================================
# scripts/install-hooks.sh
#
# Install git pre-commit hooks for the wealth-dashboard repo.
# Run once after cloning:  bash scripts/install-hooks.sh
#
# What it installs:
#   .git/hooks/pre-commit → scripts/pre-commit-personal-data-check.sh
#
# Idempotent: safe to run multiple times.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
SCRIPT_SRC="$REPO_ROOT/scripts/pre-commit-personal-data-check.sh"
HOOK_DEST="$HOOKS_DIR/pre-commit"

# ── Sanity checks ────────────────────────────────────────────────────────────
if [ ! -d "$HOOKS_DIR" ]; then
  echo "ERROR: $HOOKS_DIR not found. Is this a git repo?"
  exit 1
fi

if [ ! -f "$SCRIPT_SRC" ]; then
  echo "ERROR: $SCRIPT_SRC not found. Run from the project root."
  exit 1
fi

# ── Install ──────────────────────────────────────────────────────────────────
# Create a hook that delegates to the versioned script
cat > "$HOOK_DEST" << 'HOOKEOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Edit scripts/pre-commit-personal-data-check.sh instead.
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec "$REPO_ROOT/scripts/pre-commit-personal-data-check.sh" "$@"
HOOKEOF

chmod +x "$HOOK_DEST"
chmod +x "$SCRIPT_SRC"

echo "✅ Pre-commit hook installed: $HOOK_DEST"
echo "   Delegates to: $SCRIPT_SRC"
echo ""
echo "Test it:"
echo "  echo 'test' > /tmp/personal.sqlite"
echo "  cp /tmp/personal.sqlite personal.sqlite"
echo "  git add personal.sqlite"
echo "  git commit -m 'test' # should be blocked"
echo "  git reset HEAD personal.sqlite && rm personal.sqlite"
